version: '3.0'
services:
  web:
    image: node:alpine
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: app3.local
    ports:
      - 3000:3000
    command: node index.js

networks:
  default:
    external:
      name: nginx-proxy
